//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StrongridSimulatorGUI_MFC.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_StrongridSimulaTYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDR_StrongridPdcType            159
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_PROJECT_VIEW_POPUP          173
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_ACTIVITYLOG                 301
#define IDS_FIND_TAB                    302
#define IDR_StrongridPmuType            303
#define IDR_StrongridPhasorType         304
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_StrongridAnalogType         307
#define IDR_StrongridDigitalType        308
#define IDD_SIMGUI_PDCVIEW              310
#define IDD_SIMGUI_PMUVIEW              311
#define IDD_PHASOR                      312
#define IDD_ANALOG                      313
#define IDD_DIGITAL                     314
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_STARTSIM                    1002
#define IDC_EDIT3                       1002
#define IDC_EDIT7                       1003
#define IDC_EDIT_DATARATE               1005
#define IDC_EDIT_TIMEBASE               1006
#define IDC_BTN_STARTRTDALL             1007
#define IDC_BTN_STOPRTD_ALL             1008
#define IDC_BTN_SENDCFG2_ALL            1009
#define IDC_EDIT_TIMEBASE2              1010
#define IDC_EDIT_TIMEBASE4              1011
#define IDC_PMULIST                     1012
#define IDC_EDIT_TIMEBASE3              1013
#define IDC_RADIO1                      1014
#define IDC_RADIO2                      1015
#define IDC_RADIO3                      1016
#define IDC_RADIO4                      1017
#define IDC_RADIO5                      1018
#define IDC_RADIO6                      1019
#define IDC_RADIO7                      1020
#define IDC_RADIO8                      1021
#define IDC_MFCVSLISTBOX1               1026
#define IDC_MFCVSLISTBOX2               1027
#define IDC_MFCVSLISTBOX3               1028
#define IDC_MFCVSLISTBOX4               1029
#define IDC_MFCBUTTON1                  1030
#define IDC_CHECK4                      1038
#define IDC_CHECK5                      1039
#define IDC_CHECK6                      1040
#define IDC_CHECK7                      1041
#define IDC_CHECK8                      1042
#define IDC_MFCBUTTON3                  1043
#define IDC_COMBO2                      1045
#define IDC_COMBO3                      1046
#define IDC_COMBO1                      1046
#define IDC_COMBO4                      1047
#define IDC_EDIT4                       1047
#define IDC_COMBO5                      1048
#define IDC_BUTTON2                     1048
#define IDC_COMBO6                      1049
#define IDC_PHCFGCOMMIT                 1049
#define IDC_PHRDTCOMMIT                 1050
#define IDC_EDIT5                       1051
#define IDC_EDIT6                       1052
#define IDC_ANGCFGCOMMIT                1053
#define IDC_ANGRDTCOMMIT                1054
#define IDC_DIGCFGCOMMIT                1055
#define IDC_DIGRDTCOMMIT                1056
#define ID_FILE_SAVE32771               32771
#define ID_FILE_SAVEAS                  32772
#define ID_FILE_SAVE_MY                 32773
#define ID_FILE_SAVE_AS_MY              32774
#define ID_FILE_CLOSE_MY                32775
#define ID_NEW_NEWSOLUTION              32776
#define ID_NEW_NEWPDC                   32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
